services:
  flask: 
    build:
    volumes:
      - ./code:/code   
    image: mirali818/mirali-st125001-mla2:latest
    expose:
      - 5000 
    container_name: mirali-st125001-mla2
    # command: python /code/app.py
    # This is important for asking Traefik to use your container.
    labels:      
      - traefik.enable=true      
      - traefik.http.services.flask-st125001.loadbalancer.server.port=5000      
      - traefik.http.routers.flask-st125001.rule=Host(`st125001.ml.brain.cs.ait.ac.th`)      
      - traefik.http.routers.flask-st125001.tls=true
      - traefik.http.routers.flask-st125001.tls.certresolver=production
      - traefik.http.routers.flask-st125001.entrypoints=websecure        
    networks:
      - default
      - traefik_default

networks:
  defaults:
    traefik_default:
      external: true