services:
  dash:
    # This is for that asking the container to execute the main.py
    command: python3 code/app.py
    # The image I upload to my docker hub
    image: mirali818/mirali-st125001-mla2:${tag}
    platform: linux/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 80
    environment:
      - HOST=0.0.0.0
      - PORT=80:5000
    # This is important for asking Traefik to use your container.
    labels:      
      - traefik.enable=true      
      - traefik.http.services.web-st125001.loadbalancer.server.port=5000      
      - traefik.http.routers.web-st125001.rule=Host(`st125001.ml.brain.cs.ait.ac.th`)      
      - traefik.http.routers.web-st125001.tls=true
      - traefik.http.routers.web-st125001.tls.certresolver=production
      - traefik.http.routers.web-st125001.entrypoints=websecure    
    
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true