version: '3.8' 
services:
  flask: 
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./code:/code   
    image: mirali818/ml_125001_final
    deploy:
      resources:
        limits:
          memory: 1G 
    expose:
      - 5000 
    container_name: ml_125001_final    
    labels:      
      - traefik.enable=true      
      - traefik.http.services.flask-st125001.loadbalancer.server.port=5000      
      - traefik.http.routers.flask-st125001.rule=Host(`st125001.ml.brain.cs.ait.ac.th`)      
      - traefik.http.routers.flask-st125001.tls=true
      - traefik.http.routers.flask-st125001.tls.certresolver=production
      - traefik.http.routers.flask-st125001.entrypoints=websecure        
    networks:
      - default
      - traefik_default
networks:
  default:
  traefik_default:
      external: true