name: CI/CD Pipeline

# Name of this run
run-name: ${{ github.actor }} Building and Testing

# Trigger the workflow on tag pushes
on:
  push:
    branches:
      - main
jobs:
  # Job for building and testing
  build-test:
    runs-on: ubuntu-latest

    # Tasks, specify in list.
    steps:    
      # https://github.com/actions/checkout: will clone Git into the image
      - uses: actions/checkout@v4

      # Execute terminal command.
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v2.0
      #   with:
      #     envkey_MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      #     envkey_APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}
      #     file_name: .env
      #     fail_on_empty: true
      #     sort_keys: true     
       
      # Create Docker Network if it doesn't exist
      - name: Create Docker Network
        run: docker network create traefik_default || true
      
      # Build the Docker image
      - name: Build the Docker image
        run: docker compose -f docker-compose.yaml build
      
      # Start the Docker containers
      - name: Compose up
        run: docker compose -f docker-compose.yaml up -d   
      
      # # Execute tests using pytest
      # - name: Testing
      #   run: docker compose -f docker-compose.yaml exec flask pytest /code/test_app.py --tb=short     

      # If the testing pass, upload the image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Prepare Docker image metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:          
          images: mirali818/ml_125001_final
          tags: |
            type=schedule
            type=ref, event=branch
            type=ref, event=pr
            type=semver, pattern ={{version}}
            type=semver, pattern ={{major}}.{{minor}}
            type=semver, pattern ={{major}}
            type=semver, pattern =latest
            type=sha
      
      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}, mirali818/ml_125001_final:latest
          
  # Deployment job
  deploy:
    environment: Production
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.MLBRAIN_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.MLBRAIN_SSH_PRIVATE }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ secrets.BAZOOKA_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PASSWORD }}
          proxy_key: ${{ secrets.MLBRAIN_SSH_PRIVATE }} 
          proxy_passphrase: ${{ secrets.PASSPHRASE  }}                   
          script: |
            docker pull mirali818/ml_125001_final:latest
            # docker compose -f st125001/docker-compose.yaml down  --remove-orphans                     
            # docker compose -f st125001/docker-compose.yaml up -d
            tag=${{ github.ref_name }} docker compose -f docker-compose.yaml down
            tag=${{ github.ref_name }} docker compose -f docker-compose.yaml up -d


            #end of script